export const USERS_REQUEST = "USERS_REQUEST"
export const USERS_FAILURE = "USERS_FAILURE"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"

export const PATCH_USERS_ROLE_SUCCESS = "GET_USERS_SUCCESS"