export const PETS_REQUEST = "PETS_REQUEST"
export const PETS_FAILURE = "PETS_FAILURE"
export const GET_PETS_SUCCESS = "GET_PETS_SUCCESS"

export const PATCH_PETS_SUCCESS = "PATCH_PETS_ROLE_SUCCESS"
export const DELETE_PETS_SUCCESS = "DELETE_PETS_SUCCESS"
export const ADD_PETS_SUCCESS = "ADD_PETS_SUCCESS"
