export const GET_ADOPTION_DATA_SUCCESS = "GET_ADOPTION_DATA_SUCCESS";
export const GET_ADOPTION_DATA_REQUEST = "GET_ADOPTION_DATA_REQUEST";
export const GET_ADOPTION_DATA_FAILURE = "GET_ADOPTION_DATA_FAILURE";