

export const GET_SHELTER_SUCCESS = 'GET_SHELTER_SUCCESS';
export const GET_SHELTER_REQUEST = 'GET_SHELTER_REQUEST';
export const GET_SHELTER_FAILURE = 'GET_SHELTER_FAILURE';
export const POST_GET_STATUS = 'POST_GET_STATUS'